# Generated by Django 4.0.3 on 2022-10-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useralert',
            name='category',
            field=models.CharField(default='', max_length=255),
        ),
    ]
