# Generated by Django 4.0.3 on 2022-10-16 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_useralert_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='govalert',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='useralert',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='useralert',
            name='location',
            field=models.TextField(null=True),
        ),
    ]
